owner: q2d2
homepage_url: https://github.com/qiime2/q2-feature-classifier
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__feature_classifier
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: ''{{tool_name}}''.'
suite:
  name: suite_qiime2__feature_classifier
  description: '"Galaxy suite for QIIME 2 plugin: ''feature-classifier''. Plugin for
    taxonomic classification."'
  long_description: This QIIME 2 plugin supports taxonomic classification of features
    using a variety of methods, including Naive Bayes, vsearch, and BLAST+.
