owner: qiime2
homepage_url: https://github.com/qiime2/q2-cutadapt
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_cutadapt
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 cutadapt". Plugin for removing
    adapter sequences, primers, and other unwanted sequence from sequence data.'
  long_description: This QIIME 2 plugin uses cutadapt to work with adapters (e.g.
    barcodes, primers) in sequence data.
