owner: qiime2
homepage_url: https://github.com/qiime2/q2-composition
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_composition
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 composition". Plugin for
    compositional data analysis.'
  long_description: This QIIME 2 plugin supports methods for compositional data analysis.
