owner: q2d2
homepage_url: https://github.com/qiime2/q2-fragment-insertion
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__fragment_insertion
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2__fragment_insertion
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 fragment-insertion". Plugin
    for extending phylogenies.'
  long_description: 'No description available. See plugin website: https://github.com/qiime2/q2-fragment-insertion'
