owner: q2d2
homepage_url: https://github.com/qiime2/q2-alignment
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2_alignment
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_alignment
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 alignment". Plugin for generating
    and manipulating alignments.'
  long_description: This QIIME 2 plugin provides support for generating and manipulating
    sequence alignments.
