owner: q2d2
homepage_url: https://github.com/qiime2/q2-taxa
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2_taxa
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_taxa
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 taxa". Plugin for working
    with feature taxonomy annotations.'
  long_description: This QIIME 2 plugin provides functionality for working with and
    visualizing taxonomic annotations of features.
