owner: q2d2
homepage_url: https://github.com/qiime2/q2-diversity-lib
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__diversity_lib
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: ''{{tool_name}}''.'
suite:
  name: suite_qiime2__diversity_lib
  description: 'Galaxy suite for QIIME 2 plugin: ''diversity-lib''. Plugin for computing
    community diversity.'
  long_description: This QIIME 2 plugin computes individual metrics for  community
    alpha and beta diversity.
