owner: q2d2
homepage_url: https://github.com/qiime2/q2-quality-filter
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2_quality-filter
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_quality-filter
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 quality-filter". Plugin for
    PHRED-based filtering and trimming.'
  long_description: This QIIME 2 plugin supports filtering and trimming of sequence
    reads based on PHRED scores and ambiguous nucleotide characters.
