owner: q2d2
homepage_url: https://github.com/qiime2/q2-quality-control
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__quality_control
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: ''{{tool_name}}''.'
suite:
  name: suite_qiime2__quality_control
  description: 'Galaxy suite for QIIME 2 plugin: ''quality-control''. Plugin for quality
    control of feature and sequence data.'
  long_description: This QIIME 2 plugin supports methods for assessing and controlling
    the quality of feature and sequence data.
