owner: q2d2
homepage_url: https://github.com/qiime2/q2-diversity
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__diversity
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2__diversity
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 diversity". Plugin for exploring
    community diversity.'
  long_description: This QIIME 2 plugin supports metrics for calculating and exploring
    community alpha and beta diversity through statistics and visualizations in the
    context of sample metadata.
