owner: qiime2
categories:
  - Statistics
  - Sequence Analysis
  - Metagenomics
suite:
  name: suite_qiime2dist_tinytest2
  description: Just another example of a distribution
  include_repositories:
    - name: suite_qiime2_alignment
      owner: qiime2
