owner: qiime2
categories:
  - Sequence Analysis
  - Statistics
  - Metagenomics
suite:
  name: suite_qiime2dist_tinytest1
  description: Just an example of a distribution
  include_repositories:
    - name: suite_qiime2_metadata
      owner: qiime2
    - name: suite_qiime2_feature-table
      owner: qiime2
