owner: q2d2
homepage_url: https://github.com/qiime2/q2-demux
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_demux
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 demux". Plugin for demultiplexing
    & viewing sequence quality.'
  long_description: This QIIME 2 plugin supports demultiplexing of single-end and
    paired-end sequence reads and visualization of sequence quality information.
