owner: q2d2
type: unrestricted
homepage_url: https://github.com/bokulich-lab/q2-fondue
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__fondue
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: ''{{tool_name}}''.'
suite:
  name: suite_qiime2__fondue
  description: 'Galaxy suite for QIIME 2 plugin: ''fondue''. Plugin for fetching sequences
    and metadata.'
  long_description: This is a QIIME 2 plugin for fetching raw sequencing data andits
    associated metadata from data archives like SRA.
