owner: q2d2
homepage_url: https://github.com/qiime2/q2-sample-classifier
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__sample_classifier
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: ''{{tool_name}}''.'
suite:
  name: suite_qiime2__sample_classifier
  description: '"Galaxy suite for QIIME 2 plugin: ''sample-classifier''. Plugin for
    machine learning prediction of sample metadata."'
  long_description: This QIIME 2 plugin supports methods for supervised classification
    and regression of sample metadata, and other supervised machine learning methods.
