owner: qiime2
homepage_url: https://github.com/qiime2/q2-diversity-lib
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: "{{tool_name}}".'
suite:
  name: suite_qiime2_diversity-lib
  description: 'Galaxy suite for QIIME 2 plugin: "qiime2 diversity-lib". Plugin for
    computing community diversity.'
  long_description: This QIIME 2 plugin computes individual metrics for  community
    alpha and beta diversity.
