owner: q2d2
homepage_url: https://github.com/qiime2/q2-feature-table
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2__feature_table
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 action: ''{{tool_name}}''.'
suite:
  name: suite_qiime2__feature_table
  description: 'Galaxy suite for QIIME 2 plugin: ''feature-table''. Plugin for working
    with sample by feature tables.'
  long_description: This is a QIIME 2 plugin supporting operations on sample by feature
    tables, such as filtering, merging, and transforming tables.
