owner: q2d2
type: unrestricted
homepage_url: https://qiime2.org
remote_repository_url: https://github.com/qiime2/galaxy-tools/tree/main/tools/suite_qiime2_core__tools
categories:
  - Metagenomics
  - Sequence Analysis
  - Statistics
auto_tool_repositories:
  name_template: '{{ tool_id }}'
  description_template: 'Galaxy tool for QIIME 2 builtin: ''{{ tool_name }}''.'
suite:
  name: suite_qiime2_core__tools
  description: Galaxy suite for QIIME 2 builtins for the 'core' distribution.
  long_description: Galaxy suite for QIIME 2 builtins for the 'core' distribution.
